spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bourse_condidature_db
    username: root
    password:

  #cloud:
    #stream:
      #bindings:
        #usersTopicConsumer-in-0: # Consommation depuis le topic usersTopic
        #  destination: usersTopic
       #   group: bourse-group # Groupe de consommateurs pour le topic usersTopic
      #function:
        #definition: usersTopicConsumer
