spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bourse_condidature_db
    username: root
    password:

  cloud:
    stream:
      bindings:
        userEventsConsumer-in-0: # Consommation depuis le topic userEvents
          destination: userEvents
          group: bourse-group # Groupe de consommateurs pour le topic userEvents
        usersTopicConsumer-in-0: # Consommation depuis le topic usersTopic
          destination: usersTopic
          group: bourse-group # Groupe de consommateurs pour le topic usersTopic
      function:
        definition: userEventsConsumer;usersTopicConsumer
