spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inscription_db
    username: root
    password:

  cloud:
    stream:
      bindings:
        userEvents-out-0: # Première destination pour les événements utilisateurs
          destination: userEvents
          content-type: application/json
        usersTopic-out-0: # Deuxième destination pour la liste d'utilisateurs
          destination: usersTopic
          content-type: application/json
      function:
        definition: userEvents;usersTopic
